config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [:show]
  root 'home#index'
  resources :specialdeals, only: [:index, :show] do
    resources :charges, only: :create
  end
  resources :contact, only: [:index, :new, :create]
  namespace :admin do
    resources :specialdeals, only: [:new, :create, :show, :destroy, :update, :edit]
    resources :images, only: :create
  end
  get 'location', to: 'home#location'
  get 'about_us', to: 'home#about_us'
  get 'term', to: 'home#term'
  get 'privacy', to: 'home#privacy'
  get 'career', to: 'home#career'
  get 'isabel2jade', to: 'home#isabel2jade'
  
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :specialdeal
  belongs_to :user
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "californiaautocenter316@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :specialdeal
  belongs_to :user
end

app/models/specialdeal.rb
class Specialdeal < ApplicationRecord
  belongs_to :user
  has_many :charges
  has_many :images

  validates :title, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :description, presence: true
  validates :disclaimer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :specialdeals
  has_many :charges
  has_many :images
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.charges.create(specialdeal: current_specialdeal)

  # Amount in cents
    @amount = current_specialdeal.cost

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )

  redirect_to specialdeal_path(current_specialdeal)  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path

  end

  private

  def current_specialdeal
    @current_specialdeal ||= Specialdeal.find(params[:specialdeal_id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Contact.new
        format.html { render 'index'}
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def location
  end
  
  def about_us
  end

  def new
  end

  def term
  end

  def privacy
  end

  def career
  end

  def isabel2jade
  end
end

app/controllers/specialdeals_controller.rb
class SpecialdealsController < ApplicationController
  def index
    @specialdeals = Specialdeal.all
  end

  def show
    @specialdeal = Specialdeal.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/specialdeals_helper.rb
module SpecialdealsHelper
end

app/views/dashboards/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1>My Dashboard</h1>
  <% current_user.specialdeals.each do |specialdeal| %>
    <h3 class="text-center">
      <%= link_to specialdeal.title, admin_specialdeal_path(specialdeal) %>
    </h3>
  <% end %>  
</div>

app/views/home/about_us.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>About Us | California Auto Center</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
<style>
.grid-container {
  display: grid;
  grid-template-columns: auto auto auto;
  background-color: #f2f2f2;
  padding: 20px 20px;
}
.grid-item1, .grid-item2, .grid-item3, .grid-item4, .grid-item5, .grid-item6, .grid-item7, .grid-item8 {
  background-color: #e9f6fa;
  border: 1px solid rgba(0, 0, 0, 0.8);
  padding: 20px;
  font-size: 18px;
  text-align: left;
}

.grid-item1 {
  object-fit: cover;
  width: 100%;
  max-height: 100%;
}

.grid-item2, .grid-item4, .grid-item6, .grid-item8 {
  grid-column: 2 / span 2;
}

.wsmcccac { text-align: center; }

</style>
</head>
<body class="about_us">
<div class="booyah-box col-10 offset-1">
<br />
<h1>About Us</h1>

<b><h3>California Auto Center at Millbrae is a family owned business since 2013.  We had helped our neighborhoods on repair and maintenance of their vehicles.</h3></b>

<br />

<div class="wsmcccac">
<h2>WHY SO MANY CUSTOMERS CHOOSE CALIFORNIA AUTO CENTER</h2>
</div>

<div class="grid-container">
  
  <div class="grid-item1"><%= image_tag("cac316.jpg", :width=>"400", :height=>"270", :alt=> "California Auto Center Storefront View") %></div>
  <div class="grid-item2"><b><h3>Professional Services</h3>
<p>"Our goal is providing the best professional services to our customers."<br /><br />California Auto Center Specializes in Complete European, Japanese, Domestic Auto Repair, Tire Service, Alignment Service, Auto Body Estimate Center to San Francisco Bay Area.  We have our knowledgeable technicians to serve you and the Bay Area communities.</b></p></div><hr /><hr /><hr />
  <div class="grid-item3"><%= image_tag("millbraestation.jpg", :width=>"400", :height=>"270", :alt=> "Millbrae Bart / Caltrain Station View") %></div> 
  <div class="grid-item4"><b><h3>Conveniently Location</h3>
<p>California Auto Center is conveniently located just off the freeway 101 and 280, less than 7 miles from downtown San Mateo and less than 15 miles from downtown San Francisco. We are 3 blocks from the Millbrae BART and CALTRAIN station. For the convenience of our service customers, we offer extended service hours from Monday - Friday at 7:30AM - 6:30PM, Saturday at 8:30AM - 5:30PM.</b></p></div><hr /><hr /><hr />
  <div class="grid-item5"><%= image_tag("alignment.jpg", :width=>"400", :height=>"270", :alt=> "California Auto Center Alignment Machine View") %></div>
  <div class="grid-item6"><b><h3>Top Notch Repair and Maintenance Services</h3>
California Auto Center provides top notch fast, efficient repair and maintenance services.  Plus, our Professional Service Advisors recommend only the services your vehicle needs based on manufacturer guideline.  We will help you keep your vehicle with up to date service, explain to you what your vehicle needs are.  We want make your vehicle to stay "Top Notch" condition. </b></div><hr /><hr /><hr /> 
  <div class="grid-item7"><%= image_tag("lounge.jpg", :width=>"400", :height=>"270", :alt=> "California Auto Center Customer Lounge View") %></div>
  <div class="grid-item8"><b> <h3>Convenience and Comfort Location</h3>
California Auto Center has a wonderful customer lounge.  You can wait for your vehicle while it’s in service. We provide free Wi-Fi Internet access, comfortable seating areas.  Downtown of Millbrae is just walking distance from our location, you can shop, dine, or walk around to the wonderful local business of Millbrae.</b></div> 
</div>
</div>
</body>
</html>

app/views/home/career.html.erb
<h1>Welcome to my Awesome Career App</h1>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>California Auto Center | Millbrae Auto Service Center | Millbrae Auto Repair | Auto Mechanic Millbrae | Millbrae Tire Center</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
<style>
.grid-container {
  display: grid;
  grid: 310px / auto auto auto;
  grid-gap: 10px;
  background-color: #f2f2f2;
  padding: 20px 20px;
}
.grid-item1, .grid-item2, .grid-item3 {
  background-color: #e9f6fa;
  border: 1px solid rgba(0, 0, 0, 0.8);
  padding: 20px;
  font-size: 18px;
  text-align: right;
}

.grid-item1, .grid-item2, .grid-item3 {
  object-fit: cover;
  width: 100%;
  max-height: 100%;
}

</style>
</head>
<div class="booyah-box col-10 offset-1">
  <div class="row text-center">
    <div class="col-12 col-sm"
      <h3>FIND OUR LOCATION:<br>316 El Camino Real,<br>Millbrae, CA 94030<br>(650)692-5222</h3>
    </div>
    <div class="col-12 col-sm"
      <h3>CHECK OUT OUR COUPONS SPECIAL:<br>We have variaties of <br>SPECIAL DEALS.<br>Check us out weekly.</h3>
    </div>
    <div class="col-12 col-sm"
      <h3>ASK US AN QUESTION:<br>Send us an email to <br>ask us an question <br>or schedule an appointment.</h3>
    </div>
  </div>
<br />
  <div class="text-center">
    <h2>California Auto Center Complete Auto Repair & Tire Service (650)692-5222</h2>
  </div>
<br />
  <div id="content">
    <%= image_tag("cac316.jpg", :width=>"1150", :height=>"550", :alt=> "California Auto Center Storefront View") %>
  </div>
</div>

<br />

  <div class="grid-container">
  
  <div class="grid-item1"><%= image_tag("cac316.jpg", :width=>"400", :height=>"270", :alt=> "California Auto Center Storefront View") %></div>
  <div class="grid-item2"><b><h3>California Auto Center</h3>
<p>316 El Camino Real,<br />Millbrae, CA 94030<br />Call Us at 1-650-692-5222<br /><br /><h3>Hours of Operation</h3>Monday-Friday: 7:30AM-6:30PM<br />Saturday: 8:30AM-5:30PM<br />Sunday: Closed</b></p></div>
<div class="grid-item3"><b><h3>Conveniently Location</h3>
<p>California Auto Center is conveniently located just off the freeway 101 and 280, less than 7 miles from downtown San Mateo and less than 15 miles from downtown San Francisco. We are 3 blocks from the Millbrae BART and CALTRAIN station. For the convenience of our service customers, we offer extended service hours from Monday - Friday at 7:30AM - 6:30PM, Saturday at 8:30AM - 5:30PM.</b></p></div><hr /><hr /><hr /></div>
  <div class="booyah-box col-10 offset-1">
    <h1 align="center">Are you looking for tires?</h1><br />
    <h2 align="center">California Auto Center and TireBuyer.com had team up to offer you online tires deal.  Click on link below.</h2><br />
    <a href="http://www.tirebuyer.com/?account=376572">
    <img src="https://installers.tirebuyer.com/tirebuyerstorefront/_ui/responsive/installerportal/images/728x156-50BelowAffiliates-NewDesign2.jpg" width="1150" height="250" alt="TireBuyer Logo", class="center" />
    </a>
  </div>
</div>
<hr />
</html>

app/views/home/isabel2jade.html.erb
<h1>Welcome to my Awesome Log In App</h1>
<div class="container">
      <b>Admin</b>
      <br />
      <%= link_to 'Create a Special Deal', new_admin_specialdeal_path %>
    </div>

app/views/home/location.html.erb
<h1>Welcome to my Awesome Location App</h1>