config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [:show]
  root 'home#index'
  resources :specialdeals, only: [:index, :show] do
    resources :charges, only: :create
  end
  resources :contact, only: [:index, :new, :create]
  namespace :admin do
    resources :specialdeals, only: [:new, :create, :show, :destroy, :update, :edit]
    resources :images, only: :create
  end
  get 'location', to: 'home#location'
  get 'about_us', to: 'home#about_us'
  get 'term', to: 'home#term'
  get 'privacy', to: 'home#privacy'
  get 'career', to: 'home#career'
  get 'isabel2jade', to: 'home#isabel2jade'
  
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :specialdeal
  belongs_to :user
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "californiaautocenter316@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :specialdeal
  belongs_to :user
end

app/models/specialdeal.rb
class Specialdeal < ApplicationRecord
  belongs_to :user
  has_many :charges
  has_many :images

  validates :title, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :description, presence: true
  validates :disclaimer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :specialdeals
  has_many :charges
  has_many :images
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @specialdeal = Specialdeal.find(params[:specialdeal_id])
    @specialdeal.images.create(image_params)
    redirect_to admin_specialdeal_path(@specialdeal)
  end

  private

  def image_params
    params.require(:image).permit(:picture, :caption)
  end 

end

app/controllers/admin/specialdeals_controller.rb
class Admin::SpecialdealsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @specialdeal = Specialdeal.new
  end

  def create
    @specialdeal = current_user.specialdeals.create(specialdeal_params)
    if @specialdeal.valid?
      redirect_to admin_specialdeal_path(@specialdeal)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @specialdeal = Specialdeal.find(params[:id])
    @image = Image.new
  end

  def edit
    @specialdeal = Specialdeal.find(params[:id])

    if @specialdeal.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @specialdeal = Specialdeal.find(params[:id])
    if @specialdeal.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @specialdeal.update_attributes(specialdeal_params)
    redirect_to root_path
  end

  def destroy
    @specialdeal = Specialdeal.find(params[:id])
    if @specialdeal.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    
    @specialdeal.destroy
    redirect_to root_path
  end

  private

  helper_method :current_specialdeal
  def current_specialdeal
    @current_specialdeal ||= Specialdeal.find(params[:id])
  end

  def specialdeal_params
    params.require(:specialdeal).permit(:title, :cost, :description, :disclaimer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.charges.create(specialdeal: current_specialdeal)

  # Amount in cents
    @amount = current_specialdeal.cost

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )

  redirect_to specialdeal_path(current_specialdeal)  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path

  end

  private

  def current_specialdeal
    @current_specialdeal ||= Specialdeal.find(params[:specialdeal_id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Contact.new
        format.html { render 'index'}
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def location
  end
  
  def about_us
  end

  def new
  end

  def term
  end

  def privacy
  end

  def career
  end

  def isabel2jade
  end
end

app/controllers/specialdeals_controller.rb
class SpecialdealsController < ApplicationController
  def index
    @specialdeals = Specialdeal.all
  end

  def show
    @specialdeal = Specialdeal.find(params[:id])
  end
end

app/helpers/admin/specialdeals_helper.rb
module Admin::SpecialdealsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/specialdeals_helper.rb
module SpecialdealsHelper
end

app/views/admin/specialdeals/edit.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Special deal</h1>
  <%= simple_form_for @specialdeal, url: admin_specialdeal_path do |f| %>
    <%= f.input :title %>
    <%= f.input :cost %>
    <%= f.input :description %>
    <%= f.input :disclaimer %>
    <br />
    <%= f.submit 'Update', method: :update, class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />  
</div>

app/views/admin/specialdeals/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new special deal</h1>
  <%= simple_form_for @specialdeal, url: admin_specialdeals_path do |f| %>
    <%= f.input :title %>
    <%= f.input :cost %>
    <%= f.input :description %>
    <%= f.input :disclaimer %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />  
</div>

app/views/admin/specialdeals/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><b><%= current_specialdeal.title %></b></h1>
  <hr />
  <br />
  
  <div>
    <h2 class="text-center">
      <span class="badge badge-default">
        Special price at <%= number_to_currency (@specialdeal.cost).to_f / 100 %>
      </span> 
    </h2>
  </div>
  <br />

  <div class="row">
    <div class="col-sm-6 col-12">
      <%= simple_form_for @image, url: admin_images_path(@specialdeal) do |f| %>
        <%= f.input :caption %>
        <%= f.submit "Add a photo", class: 'btn btn-primary' %>
      <% end %>

      <% @specialdeal.images.each do |image| %>
  <div>
      <b><%= image_tag image.picture.url, class: 'img-fluid' %></b>
  </div>
<% end %>
    </div>
    <div class="col-sm-6 col-12">
      <h3><%= @specialdeal.description %></h3>
    </div>
  </div><br />
  
  <div class="row">  
    <div class="col-sm-8 col-12">
      <%= @specialdeal.disclaimer %>
    </div>

    <div class="col-sm-4 col-12 text-center">
      <% if current_user && current_user == @specialdeal.user %>
        <%= link_to 'Edit', edit_admin_specialdeal_path(@specialdeal), class: 'btn btn-primary btn-large' %>
        <%= link_to 'Delete', admin_specialdeal_path(@specialdeal), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-primary btn-large' %>
      <% end %>  
    </div>
  </div>

  <div class="text-center">
    <% if current_user && current_user == @specialdeal.user %>
    <br />
        <%= link_to 'Administer', admin_specialdeal_path(@specialdeal), class: 'btn btn-danger btn-large' %>
    <% end %> 
  </div>
</div>

app/views/specialdeals/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><b>Member Special Deals</b></h1>
  <hr />

  <% @specialdeals.each do |specialdeal| %>
    <h2 class="text-center">
      <%= specialdeal.title %></h2>
    <br />

    <h2 class="text-center">
      <span class="badge badge-default">
        Special price at <%= number_to_currency (specialdeal.cost).to_f / 100 %>
      </span> 
    </h2>

    <br />
    <div class="row">
    <div class="col-sm-8 col-12">
      <%= specialdeal.description %>
    </div>
    
    <div class="col-sm-4 col-12 text-center">
      <%= link_to 'More Details', specialdeal_path(specialdeal), class: 'btn btn-primary btn-large' %>
    </div>
  </div>
  <br class="clr" />
  <hr />
  <% end %>  
</div>

app/views/specialdeals/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">

  <h1 class="text-center"><b><%= @specialdeal.title %></b></h1>
  <hr />
  <br />

  <div>  
    <h2 class="text-center">
      <span class="badge badge-default">
        Special price at <%= number_to_currency (@specialdeal.cost).to_f / 100 %>
      </span>
    </h2>
  </div>
  <br />
  
  <div class="row">
    <div class="col-sm-6 col-12">
      <h3><% @specialdeal.images.each do |image| %></h3>
      <% end %>
    </div>
    <div class="col-sm-6 col-12">
      <h3><%= @specialdeal.description %></h3>
    </div>
  </div><br />

  <div class="row">
    <div class="col-sm-8 col-12">
      <%= @specialdeal.disclaimer %>
    </div>

    <div class="col-sm-4 col-12 text-center">
        <%= form_tag specialdeal_charges_path(@specialdeal) do %>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description= <%= @specialdeal.title %>
                  data-amount= <%= @specialdeal.cost %>
                  data-locale="auto"></script>
        <% end %>
    </div>
  </div>

  <div class="text-center">
    <% if current_user && current_user == @specialdeal.user %>
    <br />
        <%= link_to 'Administer', admin_specialdeal_path(@specialdeal), class: 'btn btn-danger btn-large' %>
    <% end %> 
  </div>
</div>