config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [:show]
  root 'home#index'
  resources :specialdeals, only: [:index, :show] do
    resources :charges, only: :create
  end
  resources :contact, only: [:index, :new, :create]
  namespace :admin do
    resources :specialdeals, only: [:new, :create, :show, :destroy, :update, :edit]
    resources :images, only: :create
  end
  get 'location', to: 'home#location'
  get 'about_us', to: 'home#about_us'
  get 'term', to: 'home#term'
  get 'privacy', to: 'home#privacy'
  get 'career', to: 'home#career'
  get 'isabel2jade', to: 'home#isabel2jade'
  
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :specialdeal
  belongs_to :user
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "californiaautocenter316@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :specialdeal
  belongs_to :user
end

app/models/specialdeal.rb
class Specialdeal < ApplicationRecord
  belongs_to :user
  has_many :charges
  has_many :images

  validates :title, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :description, presence: true
  validates :disclaimer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :specialdeals
  has_many :charges
  has_many :images
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @specialdeal = Specialdeal.find(params[:specialdeal_id])
    @specialdeal.images.create(image_params)
    redirect_to admin_specialdeal_path(@specialdeal)
  end

  private

  def image_params
    params.require(:image).permit(:picture, :caption)
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.charges.create(specialdeal: current_specialdeal)

  # Amount in cents
    @amount = current_specialdeal.cost

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )

  redirect_to specialdeal_path(current_specialdeal)  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path

  end

  private

  def current_specialdeal
    @current_specialdeal ||= Specialdeal.find(params[:specialdeal_id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Contact.new
        format.html { render 'index'}
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def location
  end
  
  def about_us
  end

  def new
  end

  def term
  end

  def privacy
  end

  def career
  end

  def isabel2jade
  end
end

app/controllers/specialdeals_controller.rb
class SpecialdealsController < ApplicationController
  def index
    @specialdeals = Specialdeal.all
  end

  def show
    @specialdeal = Specialdeal.find(params[:id])
  end
end

app/helpers/admin/specialdeals_helper.rb
module Admin::SpecialdealsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/specialdeals_helper.rb
module SpecialdealsHelper
end

app/views/contact/_contact_form.html.erb
<!-- app/views/home/_contact_form.html.erb -->

<%= form_for @contact, url: contact_index_path, remote: true do |f| %>
    <div class="col-md-6">
        <%= f.label :name %></br>
        <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :email %></br>
        <%= f.text_field :email, required: true, class: "contact-form-text-area" %></br>

      <%= f.label :message %></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
                        placeholder: "Send me a message"%></br>

      <div class= "hidden">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
      </div>

      <%= f.submit 'Send Message', class: 'btn btn-primary' %>
    </div>
  <% end %>
  <div class="col-md-6" id="flash-message">
    <%= render 'flash' %>
  </div>

app/views/contact/_flash.html.erb
<!-- app/views/home/_flash.html.erb -->

<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/contact/create.js.erb
// app/views/home/create.js.erb

// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/contact/index.html.erb
<!-- app/views/home/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Contact Us | California Auto Center</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
<style>

body {
  background-color: black;
  color: white;
}
.contact-form-text-area {
  color: black;
}
.hidden { display: none; }
.alert-error {
background-color: #f2dede;
border-color: #eed3d7;
color: #b94a48;
text-align: left;
font-size: .8em;
}

.alert-alert {
background-color: #f2dede;
border-color: #eed3d7;
color: #b94a48;
text-align: left;
font-size: .8em;
}

.alert-success {
background-color: #dff0d8;
border-color: #d6e9c6;
color: #468847;
text-align: center;
font-size: .8em;
}

.alert-notice {
background-color: #dff0d8;
border-color: #d6e9c6;
color: #468847;
text-align: left;
font-size: .8em;
}

</style>
</head>
<body class="about_us">
  <div class="booyah-box col-10 offset-1">
<br />
    <h1>Contact Us</h1>
    <div id="contact">
      <%= render 'contact_form' %>
    </div>
  </div>
</body>
</html>